<a href="https://colab.research.google.com/github/Nielatrue/deep-learning-challenge/blob/main/Starter_Code-checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns = ['EIN','NAME'], inplace=True)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
for i in application_df.columns:
    print(i, len(application_df[i].unique()))

APPLICATION_TYPE 17
AFFILIATION 6
CLASSIFICATION 71
USE_CASE 5
ORGANIZATION 4
STATUS 2
INCOME_AMT 9
SPECIAL_CONSIDERATIONS 2
ASK_AMT 8747
IS_SUCCESSFUL 2

In [4]:
# Look at APPLICATION_TYPE value counts for binning
app_counts = application_df['APPLICATION_TYPE'].value_counts()
app_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_counts[app_counts<200].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts for binning
classification_value = application_df['CLASSIFICATION'].value_counts()

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts().loc[lambda x : x >1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [12]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_value[classification_value<300].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [13]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies = pd.get_dummies(application_df)
application_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [14]:
# Split our preprocessed data into our features and target arrays
X = application_dummies.drop('IS_SUCCESSFUL', axis=1).values
y = application_dummies['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 78)

In [15]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [16]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])

hidden_nodes_layer1 = 9
hidden_nodes_layer2 = 18

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, activation='relu', input_dim=number_input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))


# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 9)                 405

 dense_1 (Dense)             (None, 18)                180

 dense_2 (Dense)             (None, 1)                 19

=================================================================
Total params: 604 (2.36 KB)
Trainable params: 604 (2.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [17]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [18]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 3s 2ms/step - loss: 0.6021 - accuracy: 0.6953
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5609 - accuracy: 0.7258
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5560 - accuracy: 0.7285
Epoch 4/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5529 - accuracy: 0.7316
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5514 - accuracy: 0.7319
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5507 - accuracy: 0.7321
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7320
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7335
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7330
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5483 - accuracy: 0.7336
Epoch 11/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5481 - accuracy: 0.7337
Epoch 12/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5479 - accuracy: 0.7334
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7341
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7345
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5471 - accuracy: 0.7339
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5473 - accuracy: 0.7337
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5467 - accuracy: 0.7352
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7335
Epoch 19/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5465 - accuracy: 0.7343
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7338
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7332
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7329
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7339
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7341
Epoch 25/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5458 - accuracy: 0.7345
Epoch 26/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5455 - accuracy: 0.7350
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7350
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7348
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7345
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7346
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7352
Epoch 32/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5448 - accuracy: 0.7339
Epoch 33/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5449 - accuracy: 0.7348
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7346
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7350
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5446 - accuracy: 0.7343
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7357
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7337
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5446 - accuracy: 0.7336
Epoch 40/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5444 - accuracy: 0.7343
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7351
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7353
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7348
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5440 - accuracy: 0.7345
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7350
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7353
Epoch 47/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5441 - accuracy: 0.7341
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7343
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7345
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7348

In [19]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5519 - accuracy: 0.7275 - 538ms/epoch - 2ms/step
Loss: 0.5518956184387207, Accuracy: 0.7274635434150696

In [23]:
# Export our model to HDF5 file
nn.save('../h5_files/AlphabetSoupCharity.h5')